receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: "platform:4317"
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://victoria-metrics:8428/api/v1/write"
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite, logging]
