packages:
  - 'libs/*'
  - 'packages/*/web'
  - 'packages/*'
  - 'packages/frontend-wrapper/*'
  - 'packages/session-replay/*'
allowBuilds:
  '@bundled-es-modules/glob': set this to true or false
  esbuild: true
  puppeteer: false
  style-dictionary: set this to true or false
