packages:
  - 'libs/*'
  - 'packages/*/web'
  - 'packages/*'
  - 'packages/frontend-wrapper/*'
  - 'packages/session-replay/*'
  - 'docs'
allowBuilds:
  '@bundled-es-modules/glob': true
  esbuild: true
  puppeteer: false
  style-dictionary: true
  '@swc/core': true
  core-js: true
